Repository github/github-mcp-server, pull requests merged in 2025-04, with the labels that each got.

#278 Add missing enum constraints
  pkg/github/code_scanning.go
  pkg/github/issues.go
  pkg/github/pullrequests.go
  pkg/github/repositories.go
  pkg/github/search.go
Labels: tool-improvement

#272 Add Tool Name property for List Code Scanning Alerts tool
  README.md
  pkg/github/code_scanning.go
  pkg/github/code_scanning_test.go
Labels: tool-improvement

#270 Add "Mark notification as done" functionality
  pkg/github/notifications.go
  pkg/github/server.go
Labels: tool-proposal

#280 Adding SecretScanning Toolset
  .gitignore
  README.md
  pkg/github/secret_scanning.go
  pkg/github/secret_scanning_test.go
  pkg/github/tools.go
Labels: tool-proposal

#274 chore: update readme for tool parititioning
  README.md
Labels: documentation

#186 Update README.md to remove mcp key on .vscode/mcp.json example
  README.md
Labels: documentation
